import { JvmInstance, RuntimesInventoryResponse } from '../api/interfaces';

export const emptyResponse: RuntimesInventoryResponse = { response: [] };

export const fooInstance: JvmInstance = {
  id: 'fooId',
  accountId: 'accountId',
  orgId: 'orgId',
  hostname: 'fooHostname',
  launchTime: 1706245200000,
  vendor: 'fooVendor',
  versionString: 'fooVersionString',
  version: 'fooVersion',
  majorVersion: 17,
  osArch: 'fooOsArch',
  processors: 12,
  heapMin: 0,
  heapMax: 9999,
  details: { 'app.name': 'foo-app' },
  created: 'fooCreated',
  javaClassVersion: 'fooJavaClassVersion',
  javaSpecificationVendor: 'fooJavaSpecificationVendor',
  javaVendor: 'fooJavaVendor',
  javaVendorVersion: 'fooJavaVendorVersion',
  javaVmName: 'fooJavaVmName',
  javaVmVendor: 'fooJavaVmVendor',
  jvmHeapGcDetails: 'fooJvmHeapGcDetails',
  jvmPid: 'fooJvmPid',
  jvmReportTime: 'fooJvmReportTime',
  systemOsName: 'fooSystemOsName',
  systemOsVersion: 'fooSystemOsVersion',
  javaHome: 'fooJavaHome',
  javaLibraryPath: 'fooJavaLibraryPath',
  javaCommand: 'fooJavaCommand',
  javaClassPath: 'fooJavaClassPath',
  jvmPackages: 'fooJvmPackages',
  jvmArgs: 'fooJvmArgs',
  workload: 'fooWorkload',
  isOcp: false,
};

export const mockInstance: JvmInstance = {
  id: 'mockId',
  accountId: 'accountId',
  orgId: 'orgId',
  hostname: 'mockHostname',
  launchTime: 1706245200001,
  vendor: 'mockVendor',
  versionString: 'mockVersionString',
  version: 'mockVersion',
  majorVersion: 17,
  osArch: 'mockOsArch',
  processors: 12,
  heapMin: 0,
  heapMax: 9999,
  details: { 'app.name': 'mock-app' },
  created: 'mockCreated',
  javaClassVersion: 'mockJavaClassVersion',
  javaSpecificationVendor: 'mockJavaSpecificationVendor',
  javaVendor: 'mockJavaVendor',
  javaVendorVersion: 'mockJavaVendorVersion',
  javaVmName: 'mockJavaVmName',
  javaVmVendor: 'mockJavaVmVendor',
  jvmHeapGcDetails: 'mockJvmHeapGcDetails',
  jvmPid: 'mockJvmPid',
  jvmReportTime: 'mockJvmReportTime',
  systemOsName: 'mockSystemOsName',
  systemOsVersion: 'mockSystemOsVersion',
  javaHome: 'mockJavaHome',
  javaLibraryPath: 'mockJavaLibraryPath',
  javaCommand: 'mockJavaCommand',
  javaClassPath: 'mockJavaClassPath',
  jvmPackages: 'mockJvmPackages',
  jvmArgs: 'mockJvmArgs',
  workload: 'mockWorkload',
  isOcp: false,
};

/**
 * Function that creates a deep copy of a passed instance by creating a string copy and parsing it.
 *
 * Useful for tests because JavaScript is pass by reference, so trying to do manipulation of the
 * test instances will result in altering the base instance values. Furthermore, instance.title
 * for the accordion toggle header is generated by the formatting function, so without working
 * on a copy the base test instance will be updated to have a title attribute.
 * @param instance JvmInstance
 * @returns a deep copy of (and not a reference to) a JvmInstance
 */
export const getCopyOfInstance = (instance: JvmInstance) => {
  return JSON.parse(JSON.stringify(instance));
};
